-- 1. SELECIONAR PARA UMA PESQUISA ESPECIFICA TODAS AS AMOSTRAS QUE AINDA NÃO FORAM DEVOLVIDAS

-- 2. RETORNAR AS 5 PESQUISAS QUE MAIS UTILIZARAM AMOSTRAS

-- 3. REUNIR TODAS AS AMOSTRAS DE TODOS OS PACIENTES NASCIDOS NUM MÊS ESPECIFICO

-- 4. REUNIR TODAS AS EXECUÇÕES QUE RECEBE ACIMA DE UM VALOR ESPECÍFICO DA AG. DE FOMENTO E QUE UTILIZARAM PELO MENOS TANTOS EXAMES

-- 5. REUNIR TODAS AS PESQUISAS RELACIONADAS A UM TAL LABORATORIO QUE TEM PACIENTES RELACIONADOS A TODOS OS ESTADOS

-- 6. DIVISÃO: RETORNAR TODAS AS UNIVERSIDADES QUE TEM VÍNCULO - PELA PESQUISA - COM TODAS AS AGÊNCIAS DE FOMENTO.
